---

- name: Clean up nginx stuff
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - /var/www/html
  - /etc/nginx/sites-available
  - /etc/nginx/sites-enabled
  - /etc/nginx/snippets/snakeoil.conf

- name: generate dhparams file
  shell: "openssl dhparam -out {{ nginx_dhparams_file }} {{ nginx_dhparams_keysize }}"
  args:
    creates: "{{ nginx_dhparams_file }}"

- name: Override default config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: systemd | nginx | reloaded

- name: Create nginx config directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  with_items:
  - /etc/nginx/conf.d
  - /etc/nginx/snippets
  - /etc/nginx/lxd.d

- name: Create letsencrypt config snippet
  template:
    src: letsencrypt.conf.j2
    dest: /etc/nginx/snippets/letsencrypt.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: systemd | nginx | reloaded

- name: ensure lxd.conf is up2date
  template:
    src: lxd.conf.j2
    dest: /etc/nginx/conf.d/lxd.conf
    owner: root
    group: root
    mode: '0644'
  notify: systemd | nginx | reloaded

- name: Ensure letsencrypt directory exists
  file:
    path: "{{ letsencrypt_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: "generate letsencrypt certificate for {{ valet_lxd_repository_domain }}"
  shell: "certbot certonly --webroot -w {{ letsencrypt_path }} --email {{ letsencrypt_email}} --non-interactive --agree-tos -d {{ valet_lxd_repository_domain }}"
  args:
    creates: "/etc/letsencrypt/live/{{ valet_lxd_repository_domain }}/fullchain.pem"
  when: (letsencrypt_dryrun is not defined) or (not letsencrypt_dryrun|bool)
